INSERT INTO category (id, name) VALUES (1, 'Common'), (2, 'Cinema'), (3, 'Sport'), (4, 'Pets'), (5, 'Music');

INSERT INTO article (title, body, category_id) VALUES
  ('The Man Within', 'Every flight begins with a fall.', 1),
  ('Consider the Lilies', 'The things I do for love.', 2),
  ('The Lathe of Heaven', 'Things are not always as they seemed, much that may seem evil can be good.', 3),
  ('Clouds of Witness', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?', 4),
  ('Eyeless in Gaza', 'There are no heroes...in life, the monsters win.', 5),
  ('Oh! To be in England', 'All dwarfs are bastards in their father`s eyes', 1),
  ('A Passage to India', 'Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.', 2),
  ('Tender Is the Night', 'Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.', 3),
  ('The Last Enemy', 'Knowledge could be more valuable than gold, more deadly than a dagger.', 4),
  ('I Know Why the Caged Bird Sings', 'When the snows fall and the white winds blow, the lone wolf dies but the pack survives.', 5),
  ('East of Eden', 'Give me honorable enemies rather than ambitious ones, and I`ll sleep more easily by night.', 1),
  ('The Moving Toyshop', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?', 2),
  ('Death Be Not Proud', 'Laughter is poison to fear.', 3),
  ('Dying of the Light', 'Give me honorable enemies rather than ambitious ones, and I`ll sleep more easily by night.', 4),
  ('The Monkey`s Raincoat', 'Do the dead frighten you?', 5),
  ('The World, the Flesh and the Devil', 'When the snows fall and the white winds blow, the lone wolf dies but the pack survives.', 1),
  ('To a God Unknown', 'Fear cuts deeper than swords.', 2),
  ('Fear and Trembling', 'A lion doesn`t concern itself with the opinion of sheep.', 3),
  ('A Time to Kill', 'Do the dead frighten you?', 4),
  ('That Good Night', 'Summer will end soon enough, and childhood as well.', 5),
  ('The Mermaids Singing', 'Do the dead frighten you?', 1),
  ('Down to a Sunless Sea', 'Winter is coming.', 2),
  ('Cover Her Face', 'Knowledge could be more valuable than gold, more deadly than a dagger.', 3),
  ('Let Us Now Praise Famous Men', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?', 3),
  ('A Time of Gifts', 'Summer will end soon enough, and childhood as well.', 4),
  ('Precious Bane', 'And I have a tender spot in my heart for cripples and bastards and broken things.', 5),
  ('The Proper Study', 'There are no heroes...in life, the monsters win.', 1),
  ('In a Dry Season', 'Never forget who you are. The rest of the world won`t. Wear it like an armor and it can never be used against you.', 2),
  ('Clouds of Witness', 'Hodor? Hodor.', 2),
  ('The Moving Toyshop', 'Never forget who you are. The rest of the world won`t. Wear it like an armor and it can never be used against you.', 3);
