DROP TABLE IF EXISTS articles;


CREATE TABLE articles (
  id bigint AUTO_INCREMENT,
  title varchar(255),
  body text
);

INSERT INTO articles (title, body) VALUES
  ('The Man Within', 'Every flight begins with a fall.'),
  ('Consider the Lilies', 'The things I do for love.'),
  ('The Lathe of Heaven', 'Things are not always as they seemed, much that may seem evil can be good.'),
  ('Clouds of Witness', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?'),
  ('Eyeless in Gaza', 'There are no heroes...in life, the monsters win.'),
  ('Oh! To be in England', 'All dwarfs are bastards in their father`s eyes'),
  ('A Passage to India', 'Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.'),
  ('Tender Is the Night', 'Power is a curious thing. Who lives, Who dies. Power resides where men believe it resides. It is a trick, A shadow on the wall.'),
  ('The Last Enemy', 'Knowledge could be more valuable than gold, more deadly than a dagger.'),
  ('I Know Why the Caged Bird Sings', 'When the snows fall and the white winds blow, the lone wolf dies but the pack survives.'),
  ('East of Eden', 'Give me honorable enemies rather than ambitious ones, and I`ll sleep more easily by night.'),
  ('The Moving Toyshop', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?'),
  ('Death Be Not Proud', 'Laughter is poison to fear.'),
  ('Dying of the Light', 'Give me honorable enemies rather than ambitious ones, and I`ll sleep more easily by night.'),
  ('The Monkey`s Raincoat', 'Do the dead frighten you?'),
  ('The World, the Flesh and the Devil', 'When the snows fall and the white winds blow, the lone wolf dies but the pack survives.'),
  ('To a God Unknown', 'Fear cuts deeper than swords.'),
  ('Fear and Trembling', 'A lion doesn`t concern itself with the opinion of sheep.'),
  ('A Time to Kill', 'Do the dead frighten you?'),
  ('That Good Night', 'Summer will end soon enough, and childhood as well.'),
  ('The Mermaids Singing', 'Do the dead frighten you?'),
  ('Down to a Sunless Sea', 'Winter is coming.'),
  ('Cover Her Face', 'Knowledge could be more valuable than gold, more deadly than a dagger.'),
  ('Let Us Now Praise Famous Men', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?'),
  ('A Time of Gifts', 'Summer will end soon enough, and childhood as well.'),
  ('Precious Bane', 'And I have a tender spot in my heart for cripples and bastards and broken things.'),
  ('The Proper Study', 'There are no heroes...in life, the monsters win.'),
  ('In a Dry Season', 'Never forget who you are. The rest of the world won`t. Wear it like an armor and it can never be used against you.'),
  ('Clouds of Witness', 'Hodor? Hodor.'),
  ('The Moving Toyshop', 'Never forget who you are. The rest of the world won`t. Wear it like an armor and it can never be used against you.'),
  ('Edna O`Brien', 'Winter is coming.'),
  ('Time of our Darkness', 'The North remembers.'),
  ('The Yellow Meads of Asphodel', 'Once you’ve accepted your flaws, no one can use them against you.'),
  ('Unweaving the Rainbow', 'The things I do for love.'),
  ('A Monstrous', 'Winter is coming.'),
  ('Fair Stood the Wind for France', 'There are no heroes...in life, the monsters win.'),
  ('Tiger! Tiger!', 'And I have a tender spot in my heart for cripples and bastards and broken things.'),
  ('Tiger! Tiger!', 'Things are not always as they seemed, much that may seem evil can be good.'),
  ('To Your Scattered Bodies Go', 'Every flight begins with a fall.'),
  ('From Here to Eternity', 'Fear cuts deeper than swords.'),
  ('Bury My Heart at Wounded Knee', 'Every flight begins with a fall.'),
  ('Where Angels Fear to Tread', 'Knowledge could be more valuable than gold, more deadly than a dagger.'),
  ('Vile Bodies', 'Things are not always as they seemed, much that may seem evil can be good.'),
  ('The Line of Beauty', 'The North remembers.'),
  ('From Here to Eternity', 'Nothing burns like the cold.'),
  ('To Your Scattered Bodies Go', 'A lion doesn`t concern itself with the opinion of sheep.'),
  ('Time To Murder And Create', 'Never forget who you are. The rest of the world won`t. Wear it like an armor and it can never be used against you.'),
  ('The Last Temptation', 'The North remembers.'),
  ('Stranger in a Strange Land', 'When you play a game of thrones you win or you die.'),
  ('This Side of Paradise', 'Winter is coming.'),
  ('A Glass of Blessings', 'Laughter is poison to fear.'),
  ('Let Us Now Praise Famous Men', 'Once you’ve accepted your flaws, no one can use them against you.'),
  ('To a God Unknown', 'And I have a tender spot in my heart for cripples and bastards and broken things.'),
  ('The Wives of Bath', 'Nothing burns like the cold.'),
  ('The Waste Land', 'Why is it that when one man builds a wall, the next man immediately needs to know what`s on the other side?'),
  ('Blue Remembered Earth', 'All dwarfs are bastards in their father`s eyes'),
  ('Alone on a Wide, Wide Sea', 'Give me honorable enemies rather than ambitious ones, and I`ll sleep more easily by night.'),
  ('That Hideous Strength', 'The things I do for love.'),
  ('A Monstrous Regiment of Women', 'Winter is coming.'),
  ('The Little Foxes', 'And I have a tender spot in my heart for cripples and bastards and broken things.');
